
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(sf)
library(USAboundaries)
library(tidyverse)
```
```{r}
#Step 1.1
counties = USAboundaries::us_counties() %>%
  filter(!state_name %in% c("Hawaii",
                            "Alaska",
                            "Puerto Rico",
                            "Guam")) %>%
  st_as_sf(coords = c("lng", "lat"), crs = 4326) %>%
  st_transform(5070)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
#Step 1.2
countycent = st_centroid(counties) 
countycent_c = st_combine(countycent)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
# Step 1.3
st_voronoi(countycent_c) 
v_grid = st_voronoi(countycent_c) %>%
  st_cast() %>% 
  st_as_sf() %>% 
  mutate(id = 1:n())

st_triangulate(countycent_c)
tri_grid = st_triangulate(countycent_c) %>%
  st_cast() %>% 
  st_as_sf() %>% 
  mutate(id = 1:n())

sqgrid = st_make_grid(counties, n=70) %>%
  st_cast() %>% 
  st_as_sf() %>% 
  mutate(id = 1:n())
  
hexgrid = st_make_grid(counties, n=70, square=FALSE) %>%
  st_cast() %>%
  st_as_sf() %>%
  mutate(id = 1:n())
```
```{r}
# Step 1.4

plot(v_grid)
plot(tri_grid)
plot(sqgrid)
plot(hexgrid)

countybound = st_union(counties) 

plot(countybound)

```

